version: 2
jobs:
  build:
    docker: 
      - image: circleci/php:7.1-node-browsers 

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      - run: composer install -n --prefer-dist
      - run: curl -s https://scripts.scantist.com/staging/scantist-bom-detect.jar --output scantist-bom-detect.jar
      - run：java -jar scantist-bom-detect.jar
